#include <stdlib.h>
#include <time.h>
#include <stdio.h>
/* more headers goes there */

/**
 * main - this function will print if the num is larger, smaller o zero
 * Description: will print something
 * Return: will return 0 when run succesful
 * betty style doc for function main goes there
 */
int main(void)
{
	int n, lastDigit;

	srand(time(0));
	n = rand() - RAND_MAX / 2;
	/*calculates last digit of the number generated by rand*/
	lastDigit = n % 10;
	printf("Last digit of %i ", n);

	if (lastDigit > 5)
		printf("and is %i greater than 5\n", lastDigit);
	else if (lastDigit == 0)
		printf("and is %i and is 0\n", lastDigit);
	else if (lastDigit < 6 && lastDigit != 0)
		printf("and is %i less than 6 and not 0\n", lastDigit);
	return (0);
}
